### ISSUE TITLE
awsl

### ISSUE THREAD

**Issue by xiangyx** [Halldor-Laxness/Advent_of_Code_2020#4]
一不小心，把lzy和我merge了淦

**Comment by changgg** [comment]
哈皮

**Comment by xiangyx** [comment]
![image](https://user-images.githubusercontent.com/28193915/113936085-9c4de900-97f7-11eb-9c4c-f7b2b2c4f8b1.png)

**Comment by xiangyx** [comment]
唱国歌牛逼！
